force-app/main/default/objects/Sports_Registration__c/Sports_Registration__c.object-meta.xml
<CustomObject>
    <label>Sports Registration</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sports Registration Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sports_Registration__c/fields/Number_of_Players__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Players__c</fullName>
    <label>Number of Players</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sports_Registration__c/fields/Registration_Fee__c.field-meta.xml
<CustomField>
    <fullName>Registration_Fee__c</fullName>
    <description>Registration fee For Sports</description>
    <label>Registration Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sports_Registration__c/fields/Sport__c.field-meta.xml
<CustomField>
    <fullName>Sport__c</fullName>
    <label>Sport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cricket</fullName>
            </value>
            <value>
                <fullName>Kabaddi</fullName>
            </value>
            <value>
                <fullName>Volley Ball</fullName>
            </value>
            <value>
                <fullName>Throw Ball</fullName>
            </value>
            <value>
                <fullName>Basket Ball</fullName>
            </value>
            <value>
                <fullName>Tennikoit</fullName>
            </value>
            <value>
                <fullName>Badminton</fullName>
            </value>
            <value>
                <fullName>Kho-Kho</fullName>
            </value>
            <value>
                <fullName>Chess</fullName>
            </value>
            <value>
                <fullName>Tug of War</fullName>
            </value>
            <value>
                <fullName>Carroms</fullName>
            </value>
            <value>
                <fullName>Table-Tennis</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SportsRegistrationController.cls
public with sharing class SportsRegistrationController {
    @AuraEnabled
    public static void createRegistration(String sport, String teamName, Integer players, Decimal fee) {
        Sports_Registration__c reg = new Sports_Registration__c();
        reg.Name = teamName; // use standard Name
        reg.Sport__c = sport;
        reg.Number_of_Players__c = players;
        reg.Registration_Fee__c = fee;
        insert reg;
    }
}